version: '3'


services:
  authenticaton-service:
    build:
      context: .
      dockerfile: ./authentication-service.dockerfile
    restart: 'no'
    ports: 
      - "8091:8091"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=potgres port=5432 user=postgres password=password dbname=users sslmode=disable timzone=UTC connect_timeout=5"
    

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5532:5432" #using 5532 port, because 5432 and 5433 are used by my host machine (i do have my own postgres on my host machine)
    restart: 'no'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql